/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package compiler;

import compiler.Exceptions.ParserExceptions.ParserException;
import compiler.Exceptions.SemanticException.SemanticErrorException;
import compiler.Lexer.Lexer;
import compiler.Lexer.Symbol;
import compiler.Parser.AST.Program;
import compiler.Parser.Parser;
import compiler.SemanticAnalysis.SemanticAnalysis;

import java.io.*;


public class Compiler {
    public static void main(String[] args) throws IOException, ParserException, SemanticErrorException {

        boolean debugModeLexer = false;
        boolean debugModeParser = false;
        boolean debugModeSemanticAnalysis = false;
        String filePath = null;

        // Parse command-line arguments
        for (int i = 0; i < args.length; i++) {
            if ("-lexer".equals(args[i])) {
                debugModeLexer = true;
            } else if("-parser".equals(args[i]) || args[i] == "-parser"){
                debugModeParser = true;
            } else if("-semantic".equals(args[i]) || args[i] == "-semantic"){
                debugModeSemanticAnalysis = true;
            }
            else {
                // Assuming the file path comes after the -lexer flag
                filePath = args[i];
            }
        }
        // Check if file path is provided
        if (filePath == null) {
            System.err.println("Usage: javac Main.java -lexer -parser -semantic <filepath>");
            System.exit(1); // Exit with error
        }

        FileReader fileReader = new FileReader(filePath);
        SemanticAnalysis s = new SemanticAnalysis(fileReader, debugModeLexer, debugModeParser, debugModeSemanticAnalysis);
        s.performSemanticAnalysis();



    }
}
